# Generated by Django 3.1.1 on 2020-09-18 13:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataCall',
            fields=[
                ('call_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('investment_name', models.TextField(max_length=30)),
                ('capital_requirement', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='DataCommitment',
            fields=[
                ('commitment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='DataFund',
            fields=[
                ('fund_id', models.IntegerField(primary_key=True, serialize=False)),
                ('fundName', models.TextField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='DataFundInvestment',
            fields=[
                ('dfi_id', models.IntegerField(primary_key=True, serialize=False)),
                ('investment_amount', models.IntegerField()),
                ('call_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.datacall')),
                ('commitment_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.datacommitment')),
                ('fund_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.datafund')),
            ],
        ),
        migrations.AddField(
            model_name='datacommitment',
            name='fund_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.datafund'),
        ),
    ]
