# Generated by Django 3.1.1 on 2020-09-20 14:00

from django.db import migrations
from datetime import date


def generate_initial_data(apps, schema_editor):
    Datafund = apps.get_model('app', 'DataFund')
    Datafund(fundName='Fund 1').save()
    Datafund(fundName='Fund 2').save()
    Datafund(fundName='Fund 3').save()
    Datafund(fundName='Fund 4').save()
    Datafund(fundName='Fund 5').save()

    Datacommitment = apps.get_model('app', 'DataCommitment')
    Datacommitment(fund_id=Datafund.objects.get(fundName='Fund 1'), date=date(2017, 12, 31), amount=10000000).save()
    Datacommitment(fund_id=Datafund.objects.get(fundName='Fund 2'), date=date(2018, 3, 31), amount=15000000).save()
    Datacommitment(fund_id=Datafund.objects.get(fundName='Fund 3'), date=date(2018, 6, 30), amount=10000000).save()
    Datacommitment(fund_id=Datafund.objects.get(fundName='Fund 4'), date=date(2018, 9, 30), amount=15000000).save()
    Datacommitment(fund_id=Datafund.objects.get(fundName='Fund 1'), date=date(2018, 12, 31), amount=10000000).save()

class Migration(migrations.Migration):
    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(generate_initial_data),
    ]
